right_format = """$time"""

[directory]
fish_style_pwd_dir_length = 1 

[aws]
disabled = true

[golang]
disabled = false

[rust]
disabled = false

[python]
disabled = false

[nodejs]
disabled = false

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = "?${count}"
stashed = "\\$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[time]
disabled = false
time_format = "%d/%m/%y %H:%M:%S"
