# import = [
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
option_as_alt = "Both"
startup_mode = "Maximized"

[scrolling]
history = 10000

[env]
TERM = "xterm-256color"
